### ISSUE TITLE
msgpack.decode(new Uint8Array(data)) leads to "Uncaught TypeError: this.readUInt32BE is not a function"

### ISSUE THREAD

**Issue by kochelmonster** [kawanet/msgpack-lite#16]
I tracked that down to the following method in decode-buffer.js:
```javascript
DecodeBuffer.prototype.append = function(chunk) {
  var prev = this.offset ? this.buffer.slice(this.offset) : this.buffer;
  this.buffer = prev ? Buffer.concat([prev, chunk]) : chunk;
  this.offset = 0;
};
```
I think the buffer assignment has to be replaced to:
```javascript
  this.buffer = prev ? Buffer.concat([prev, chunk]) : Buffer(chunk);
```

**Comment by kawanet** [comment]
The current version of `msgpack.decode` requests a Buffer instance instead of a native Uint8Array instance as a chunk. Buffer has some of utility methods compared to Uint8Array's.

I guess `msgpack.decode(Buffer(new Uint8Array(data))` would work.

By the way, the module was started when node.js was v0.12. It seems that Buffer implementation is changed since io.js. The module may have better to support Uint8Array. It'd fast on browsers.

```
$ ~/.nvm/v0.10.41/bin/node -pe 'Buffer(1) instanceof Uint8Array'
false
$ ~/.nvm/versions/node/v0.12.9/bin/node -pe 'Buffer(1) instanceof Uint8Array'
false
$ ~/.nvm/versions/node/v4.2.3/bin/node -pe 'Buffer(1) instanceof Uint8Array'
true
$ ~/.nvm/versions/node/v5.3.0/bin/node -pe 'Buffer(1) instanceof Uint8Array'
true
```

**Comment by kochelmonster** [comment]
I use msgpack in chrome. Buffer is not exported to global namespace.

**Comment by kawanet** [comment]
> I use msgpack in chrome. Buffer is not exported to global namespace.

I see. Now it accepts Uint8Array instance since version 0.1.17!

```js
var data = [0x81, 0xA3, 0x66, 0x6F, 0x6F, 0xA3, 0x62, 0x61, 0x72];
msgpack.decode(new Uint8Array(data)); // => {foo: "bar"}
```
