### ISSUE TITLE
BufferShortageError on Mac

### ISSUE THREAD

**Issue by fed135** [kawanet/msgpack-lite#36]
I've tried multiple versions of Node on Mac and I keep getting BufferShortageError.
This occurs during benchmarking with buffers of around 5kb. This doesn't happen on Linux.

You can get the code here: https://github.com/fed135/Kalm/tree/master/tests/benchmarks
(You can change the duration of the tests in /tests/settings.js)

    node tests/benchmarks

    /Users/frederic/node/Kalm/node_modules/msgpack-lite/lib/read-format.js:74
    if (end > buffer.length) throw new BufferShortageError();

**Comment by kawanet** [comment]
@fed135 

The error happens when the app does not give enough length of Buffer to `msgpack.decode()`.
A valid msgpack message may be divided into multiple chunks when sending through a network stream.

```js
        /**
         * Handler for receiving data through the listener
         * @private
         * @method handleRequest
         * @memberof Client
         * @param {Buffer} evt The data received
         */
        handleRequest(evt) {
                var raw = encoders.resolve(this.options.encoder).decode(evt);
                if (raw && raw.length) {
                        if (this.channels.hasOwnProperty(raw[0])) {
                                this.channels[raw[0]].handleData(raw[1]);
                        }
                }
        }
```

I have not dived into the code of Kalm, however, I guess the OS X may divide the receiving data for 8192 bytes chunk each.

Use the Stream model or the Event model of the msgpack-lite module.
Those could manage the multiple chunks divided.

**Comment by fed135** [comment]
Thanks, I will try that
