### ISSUE TITLE
The result of msgpack-lite is different from  msgpack official tool.

### ISSUE THREAD

**Issue by finscn** [kawanet/msgpack-lite#67]
the test data : 
```
    {
            a: [127, 127, 127],
            b: [255, 255, 255],
            c: [32767, 32767, 32767],
            d: [65535, 65535, 65535],
            e: [2147483647, 2147483647, 2147483647],
            f: [4294967295, 4294967295, 4294967295],
            g: [3.14, 3.14, 3.14],
            h: [2.71, 2.71, 2.71],
            i: [true, true, true],
            j: ["c'est bien! 哈哈", "je le sais", "c'est pas bon"],
     }
```

When I use   http://msgpack.org/ online test to encode data, the size of result is 189.
When I use msgpack-lite encode , the size is 201.

**Comment by kawanet** [comment]
Do you have any problem at decoded objects?
Please don't compare the encoded byte arrays but compare the objects decoded.
Because each encoders would have a difference on optimizing for encoded byte array.

For instance, http://msgpack.org/ encodes `4294967295` to `ce ff ff ff ff`.
http://kawanet.github.io/msgpack-lite/ encodes it to `CB 41 EF FF FF FF E0 00 00`.
Those are same value.
JavaScript does not have the primitive unsigned 32bit integer type.

**Comment by finscn** [comment]
Oh, I see. Thanks. 

It could be decoded.
