### ISSUE TITLE
Compatability with old PHP Package

### ISSUE THREAD

**Issue by karljakober** [kawanet/msgpack-lite#68]
Hello! Im trying to decode a buffer encoded by and old old version of php msgpack

https://github.com/onlinecity/msgpack-php

`���type�data��follows���name�ActionBa5tard�variation��isTestãnsp�/��rooms��6557A74B19C2EBCA0B2A�flags�`

receiving the error

```
/home/vagrant/io/node_modules/msgpack-lite/lib/read-core.js:24
    if (!func) throw new Error("Invalid type: " + (type ? ("0x" + type.toString(16)) : type));
                     ^
Error: Invalid type: 0x�
```

The end goal would be to eventually use php-webpack, but I can nither update to msgpack-lite nor update php-webpack official package without downtime in connectivity between my IO server and my PHP emits

My hope is to get msgpack-lite working with my old php-webpack emits, and then update php-webpack with no downtime

Any ideas on how I can accomplish this?

**Comment by dchenk** [comment]
That PHP library seems so old and out of date since nobody is maintaining it that you probably shouldn't be using it in the first place. @kawanet I recommend closing this issue.

**Comment by kawanet** [comment]
@KarlJakober  I just guess the problem may exist not on the PHP library but on the JavaScript application. The error message below looks that the `type` value is not a number but a string. The application might read the input octets as a string instead of an ArrayBuffer or a Buffer.

```txt
/home/vagrant/io/node_modules/msgpack-lite/lib/read-core.js:24
    if (!func) throw new Error("Invalid type: " + (type ? ("0x" + type.toString(16)) : type));
                     ^
Error: Invalid type: 0x�
```

Put your input octets (of hex representation) encoded by the PHP library at http://kawanet.github.io/msgpack-lite/ demo page. If you got the same or another error, please open the issue again.

Thanks @dchenk
